spring:
  profiles:
    active: cloud
---
spring:
  profiles: cloud
  jpa:
    show_sql: false
    hibernate:
      ddl-auto: none
  datasource:
     platform: hsqldb
server:
  port: 9006
eureka:
  instance:
    hostname: ${cloud_host}
    nonSecurePort: 9006
ribbon:
  eureka:
    enabled: true
namespace:
  host: testjms1001.servicebus.windows.net
  username: ReadWrite
  password: BTr6/sSB6TfXwGUvKiaLZjpzfuvOY8m1XxPEawB864E=
---
spring:
  profiles: local
  jpa:
    show_sql: false
    hibernate:
      ddl-auto: none
  datasource:
    platform: hsqldb
server:
  port: 9006
eureka:
  instance:
    preferIpAddress: true
ribbon:
  eureka:
    enabled: true
namespace:
  host: testjms1001.servicebus.windows.net
  username: ReadWrite
  password: BTr6/sSB6TfXwGUvKiaLZjpzfuvOY8m1XxPEawB864E=
