spring:
  profiles:
    active: docker
---
spring:
  profiles: cloud
  cloud:
    config:
      enabled: true
server:
  port: 9004
neo4j:
  uri: http://localhost:7474/db/data/
  username: neo4j
  password: graphdb
  bootstrap: true
aws:
  s3:
    url: https://s3.amazonaws.com/dataset-demos
eureka:
  client:
    serviceUrl:
      defaultZone: http://${cloud_host}:8761/eureka/
  instance:
    hostname: ${cloud_host}
    nonSecurePort: 9004
ribbon:
  eureka:
    enabled: true
namespace:
  host: testjms1001.servicebus.windows.net
  username: ReadWrite
  password: BTr6/sSB6TfXwGUvKiaLZjpzfuvOY8m1XxPEawB864E=
---
spring:
  profiles: docker
server:
  port: 9004
neo4j:
  uri: http://localhost:7474/db/data/
  username: neo4j
  password: graphdb
  bootstrap: true
aws:
  s3:
    url: https://s3.amazonaws.com/dataset-demos
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true
ribbon:
  eureka:
    enabled: true
namespace:
  host: testjms1001.servicebus.windows.net
  username: ReadWrite
  password: BTr6/sSB6TfXwGUvKiaLZjpzfuvOY8m1XxPEawB864E=