---
spring:
  profiles:
    active: cloud
---
spring:
  profiles:
    name: cloud
  cloud:
    config:
      discovery:
        enabled: true
      server:
        git:
          uri: https://github.com/stansa/configuration
          searchPaths: ConfigData
encrypt:
  failOnError: false
eureka:
  instance:
    hostname: ${cloud_host}
    nonSecurePort: 8888
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${cloud_host}:8761/eureka/
server:
  port: 8888
info:
  description: Config Server
  url: https://github.com/stansa/configuration
---
spring:
  profiles:
    name: docker
  cloud:
    config:
      discovery:
        enabled: true
      server:
        git:
          uri: https://github.com/stansa/configuration
          searchPaths: ConfigData
encrypt:
  failOnError: false
eureka:
  instance:
    hostname: configServer
    preferIpAddress: true
    defaultZone: http://discovery:8761/eureka/
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
server:
  port: 8888
info:
  description: Config Server
  url: https://github.com/stansa/configuration