spring:
  profiles:
    active: docker
---
spring:
  profiles: cloud
  jpa:
    show_sql: false
    hibernate:
      ddl-auto: none
  datasource:
     platform: hsqldb
server:
  port: 9006
eureka:
  client:
    serviceUrl:
      defaultZone: http://${cloud_host}:8761/eureka/
  instance:
    hostname: ${cloud_host}
    nonSecurePort: 9006
ribbon:
  eureka:
    enabled: true
---
spring:
  profiles: docker
  jpa:
    show_sql: false
    hibernate:
      ddl-auto: none
  datasource:
    platform: hsqldb
server:
  port: 9006
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true
ribbon:
  eureka:
    enabled: true