spring:
  profiles:
    active: cloud
---
spring:
  profiles: cloud
  cloud:
    config:
      discovery:
        enabled: true
server:
  port: 8761
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
eureka:
  instance:
    hostname: ${cloud_host}
    nonSecurePort: 8761
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${cloud_host}:8761/eureka/
---
spring:
  profiles: docker
server:
  port: 8761
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: true
eureka:
  instance:
    hostname: discovery
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
